# Generated by Django 6.0.7 on 2026-07-20 14:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='codigo_validacao',
            field=models.UUIDField(default=uuid.UUID('4093cc9a-90b1-4c43-8560-ff8f5cb640f9'), unique=True),
        ),
    ]
