# Generated by Django 6.0.7 on 2026-07-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('publicado', 'Publicado'), ('cancelado', 'Cancelado'), ('encerrado', 'Encerrado')], default='publicado', max_length=20),
        ),
        migrations.AddField(
            model_name='tipoingresso',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipoingresso',
            name='limite_por_comprador',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
